# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the Python version and other tools you might need
python:
  version: 3.12  # Specify the Python version you need
  install:
    - requirements: requirements.txt  # Install dependencies from requirements.txt

# Set the Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Environment variables (optional, for custom setups)
build:
  environment:
    READTHEDOCS: True
